
package com.sain.commerce.payment.method.irankish.ikc.verify;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IVerify", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IVerify {


    /**
     * 
     * @param merchantId
     * @param referenceNumber
     * @param sha1Key
     * @param token
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "KicccPaymentsVerification", action = "http://tempuri.org/IVerify/KicccPaymentsVerification")
    @WebResult(name = "KicccPaymentsVerificationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "KicccPaymentsVerification", targetNamespace = "http://tempuri.org/", className = "com.sain.commerce.payment.method.irankish.ikc.verify.KicccPaymentsVerification")
    @ResponseWrapper(localName = "KicccPaymentsVerificationResponse", targetNamespace = "http://tempuri.org/", className = "com.sain.commerce.payment.method.irankish.ikc.verify.KicccPaymentsVerificationResponse")
    public Long kicccPaymentsVerification(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "merchantId", targetNamespace = "http://tempuri.org/")
        String merchantId,
        @WebParam(name = "referenceNumber", targetNamespace = "http://tempuri.org/")
        String referenceNumber,
        @WebParam(name = "sha1Key", targetNamespace = "http://tempuri.org/")
        String sha1Key);

    /**
     * 
     * @param referenceNo
     * @param merchantId
     * @param invoiceNo
     * @return
     *     returns com.sain.commerce.payment.method.irankish.ikc.verify.TransactionModel
     */
    @WebMethod(action = "http://tempuri.org/IVerify/getTransaction")
    @WebResult(name = "getTransactionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getTransaction", targetNamespace = "http://tempuri.org/", className = "com.sain.commerce.payment.method.irankish.ikc.verify.GetTransaction")
    @ResponseWrapper(localName = "getTransactionResponse", targetNamespace = "http://tempuri.org/", className = "com.sain.commerce.payment.method.irankish.ikc.verify.GetTransactionResponse")
    public TransactionModel getTransaction(
        @WebParam(name = "merchantId", targetNamespace = "http://tempuri.org/")
        String merchantId,
        @WebParam(name = "invoiceNo", targetNamespace = "http://tempuri.org/")
        String invoiceNo,
        @WebParam(name = "referenceNo", targetNamespace = "http://tempuri.org/")
        String referenceNo);

    /**
     * 
     * @param amount
     * @param merchantId
     * @param invoiceNo
     * @return
     *     returns com.sain.commerce.payment.method.irankish.ikc.verify.TransactionModel
     */
    @WebMethod(action = "http://tempuri.org/IVerify/getLimitedTransacction")
    @WebResult(name = "getLimitedTransacctionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getLimitedTransacction", targetNamespace = "http://tempuri.org/", className = "com.sain.commerce.payment.method.irankish.ikc.verify.GetLimitedTransacction")
    @ResponseWrapper(localName = "getLimitedTransacctionResponse", targetNamespace = "http://tempuri.org/", className = "com.sain.commerce.payment.method.irankish.ikc.verify.GetLimitedTransacctionResponse")
    public TransactionModel getLimitedTransacction(
        @WebParam(name = "merchantId", targetNamespace = "http://tempuri.org/")
        String merchantId,
        @WebParam(name = "invoiceNo", targetNamespace = "http://tempuri.org/")
        String invoiceNo,
        @WebParam(name = "amount", targetNamespace = "http://tempuri.org/")
        String amount);

    /**
     * 
     * @param offset
     * @param merchantId
     * @param limit
     * @return
     *     returns com.sain.commerce.payment.method.irankish.ikc.verify.ArrayOftransactionModel
     */
    @WebMethod(action = "http://tempuri.org/IVerify/getDailyTransaction")
    @WebResult(name = "getDailyTransactionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getDailyTransaction", targetNamespace = "http://tempuri.org/", className = "com.sain.commerce.payment.method.irankish.ikc.verify.GetDailyTransaction")
    @ResponseWrapper(localName = "getDailyTransactionResponse", targetNamespace = "http://tempuri.org/", className = "com.sain.commerce.payment.method.irankish.ikc.verify.GetDailyTransactionResponse")
    public ArrayOftransactionModel getDailyTransaction(
        @WebParam(name = "merchantId", targetNamespace = "http://tempuri.org/")
        String merchantId,
        @WebParam(name = "offset", targetNamespace = "http://tempuri.org/")
        String offset,
        @WebParam(name = "limit", targetNamespace = "http://tempuri.org/")
        String limit);

    /**
     * 
     * @param fromDate
     * @param offset
     * @param merchantId
     * @param toDate
     * @param limit
     * @return
     *     returns com.sain.commerce.payment.method.irankish.ikc.verify.ArrayOftransactionModel
     */
    @WebMethod(action = "http://tempuri.org/IVerify/getOfflineTransaction")
    @WebResult(name = "getOfflineTransactionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getOfflineTransaction", targetNamespace = "http://tempuri.org/", className = "com.sain.commerce.payment.method.irankish.ikc.verify.GetOfflineTransaction")
    @ResponseWrapper(localName = "getOfflineTransactionResponse", targetNamespace = "http://tempuri.org/", className = "com.sain.commerce.payment.method.irankish.ikc.verify.GetOfflineTransactionResponse")
    public ArrayOftransactionModel getOfflineTransaction(
        @WebParam(name = "merchantId", targetNamespace = "http://tempuri.org/")
        String merchantId,
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        String toDate,
        @WebParam(name = "offset", targetNamespace = "http://tempuri.org/")
        String offset,
        @WebParam(name = "limit", targetNamespace = "http://tempuri.org/")
        String limit);

    /**
     * 
     * @param fromDate
     * @param offset
     * @param merchantId
     * @param toDate
     * @param ibanNo
     * @param limit
     * @return
     *     returns com.sain.commerce.payment.method.irankish.ikc.verify.ArrayOftransactionModel
     */
    @WebMethod(action = "http://tempuri.org/IVerify/getTransactionByIban")
    @WebResult(name = "getTransactionByIbanResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getTransactionByIban", targetNamespace = "http://tempuri.org/", className = "com.sain.commerce.payment.method.irankish.ikc.verify.GetTransactionByIban")
    @ResponseWrapper(localName = "getTransactionByIbanResponse", targetNamespace = "http://tempuri.org/", className = "com.sain.commerce.payment.method.irankish.ikc.verify.GetTransactionByIbanResponse")
    public ArrayOftransactionModel getTransactionByIban(
        @WebParam(name = "merchantId", targetNamespace = "http://tempuri.org/")
        String merchantId,
        @WebParam(name = "IbanNo", targetNamespace = "http://tempuri.org/")
        String ibanNo,
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        String toDate,
        @WebParam(name = "offset", targetNamespace = "http://tempuri.org/")
        String offset,
        @WebParam(name = "limit", targetNamespace = "http://tempuri.org/")
        String limit);

    /**
     * 
     * @param merchantId
     * @param key
     * @return
     *     returns com.sain.commerce.payment.method.irankish.ikc.verify.ArrayOfCardModel
     */
    @WebMethod(operationName = "GetCardsPerKey", action = "http://tempuri.org/IVerify/GetCardsPerKey")
    @WebResult(name = "GetCardsPerKeyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCardsPerKey", targetNamespace = "http://tempuri.org/", className = "com.sain.commerce.payment.method.irankish.ikc.verify.GetCardsPerKey")
    @ResponseWrapper(localName = "GetCardsPerKeyResponse", targetNamespace = "http://tempuri.org/", className = "com.sain.commerce.payment.method.irankish.ikc.verify.GetCardsPerKeyResponse")
    public ArrayOfCardModel getCardsPerKey(
        @WebParam(name = "merchantId", targetNamespace = "http://tempuri.org/")
        String merchantId,
        @WebParam(name = "key", targetNamespace = "http://tempuri.org/")
        String key);

}
