
package com.sain.commerce.payment.method.irankish.ikc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ITokens", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ITokens {


    /**
     * 
     * @param amount
     * @param specialPaymentId
     * @param merchantId
     * @param paymentId
     * @param description
     * @param invoiceNo
     * @param revertURL
     * @return
     *     returns com.sain.commerce.payment.method.irankish.ikc.TokenResponse
     */
    @WebMethod(operationName = "MakeToken", action = "http://tempuri.org/ITokens/MakeToken")
    @WebResult(name = "MakeTokenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MakeToken", targetNamespace = "http://tempuri.org/", className = "com.sain.commerce.payment.method.irankish.ikc.MakeToken")
    @ResponseWrapper(localName = "MakeTokenResponse", targetNamespace = "http://tempuri.org/", className = "com.sain.commerce.payment.method.irankish.ikc.MakeTokenResponse")
    public TokenResponse makeToken(
        @WebParam(name = "amount", targetNamespace = "http://tempuri.org/")
        String amount,
        @WebParam(name = "merchantId", targetNamespace = "http://tempuri.org/")
        String merchantId,
        @WebParam(name = "invoiceNo", targetNamespace = "http://tempuri.org/")
        String invoiceNo,
        @WebParam(name = "paymentId", targetNamespace = "http://tempuri.org/")
        String paymentId,
        @WebParam(name = "specialPaymentId", targetNamespace = "http://tempuri.org/")
        String specialPaymentId,
        @WebParam(name = "revertURL", targetNamespace = "http://tempuri.org/")
        String revertURL,
        @WebParam(name = "description", targetNamespace = "http://tempuri.org/")
        String description);

    /**
     * 
     * @param amount
     * @param specialPaymentId
     * @param merchantId
     * @param paymentId
     * @param extraParam1
     * @param description
     * @param extraParam2
     * @param extraParam3
     * @param extraParam4
     * @param invoiceNo
     * @param revertURL
     * @return
     *     returns com.sain.commerce.payment.method.irankish.ikc.TokenResponse
     */
    @WebMethod(operationName = "MakeSpecialToken", action = "http://tempuri.org/ITokens/MakeSpecialToken")
    @WebResult(name = "MakeSpecialTokenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MakeSpecialToken", targetNamespace = "http://tempuri.org/", className = "com.sain.commerce.payment.method.irankish.ikc.MakeSpecialToken")
    @ResponseWrapper(localName = "MakeSpecialTokenResponse", targetNamespace = "http://tempuri.org/", className = "com.sain.commerce.payment.method.irankish.ikc.MakeSpecialTokenResponse")
    public TokenResponse makeSpecialToken(
        @WebParam(name = "amount", targetNamespace = "http://tempuri.org/")
        String amount,
        @WebParam(name = "merchantId", targetNamespace = "http://tempuri.org/")
        String merchantId,
        @WebParam(name = "invoiceNo", targetNamespace = "http://tempuri.org/")
        String invoiceNo,
        @WebParam(name = "paymentId", targetNamespace = "http://tempuri.org/")
        String paymentId,
        @WebParam(name = "specialPaymentId", targetNamespace = "http://tempuri.org/")
        String specialPaymentId,
        @WebParam(name = "revertURL", targetNamespace = "http://tempuri.org/")
        String revertURL,
        @WebParam(name = "description", targetNamespace = "http://tempuri.org/")
        String description,
        @WebParam(name = "extraParam1", targetNamespace = "http://tempuri.org/")
        String extraParam1,
        @WebParam(name = "extraParam2", targetNamespace = "http://tempuri.org/")
        String extraParam2,
        @WebParam(name = "extraParam3", targetNamespace = "http://tempuri.org/")
        String extraParam3,
        @WebParam(name = "extraParam4", targetNamespace = "http://tempuri.org/")
        String extraParam4);

}
